version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
#    command:
#      - ["dockerize","-wait", "tcp://]
    entrypoint: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
